package com.sid.autoEcole.exeptions;

public enum ExceptionType {

    SERVER_ERROR, NOT_FOUND, EMPTY, BAD_REQUEST, NON_SERIALIZABLE, STUDENT_ALREADY_EXISTS,
    FORBIDDEN, INVALID_ARGUMENTS, INTERNAL_ERROR, REFERENCE_ALREADY_EXISTS;




}
